version: '2'
services:
  influxdb:
    image: influxdb:1.1.1
    volumes:
      - data/influxdb:/var/lib/influxdb
      - influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - '8083:8083'
      - '8086:8086'
  grafana:
    image: grafana/grafana:4.0.2
    volumes:
      - data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_PATHS_DATA=/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
